name: Run GoTest

on:
  pull_request:
    branches:
      - tkmain
  push:
    branches:
      - tkmain

concurrency:
  group: test-arm64-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    name: Test ARM64
    runs-on: arm64_runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get install -y pkg-config gcc libseccomp-dev

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20.6

      - name: Install dependencies
        run: go mod tidy

      - name: Compile library
        run: bash ./build/build_arm64.sh

      - name: Setup Nodejs20.11.1
        uses: actions/setup-node@v3
        with:
          node-version: '20.11.1'

      - name: Setup Python3.10
        run: sudo apt-get install -y python3.10 python3-pip

      - name: Install Python dependencies
        run: pip install httpx requests jinja2

      - name: Link Go
        run: sudo ln -s "$(which go)" /usr/local/bin/go

      - name: Run Intgeration tests
        run: sudo go test -timeout 120s -v ./tests/integration_tests/...
        env:
          PYTHON_PATH: /usr/bin/python3.10
